In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import os
import psycopg2
import re

In [2]:
def extract_batting_data(series_id, match_id):
    URL = 'https://www.espncricinfo.com/series/'+ str(series_id) + '/scorecard/' + str(match_id)
    return URL

In [3]:
#IPL2023
ls = []
for i in range(1359475, 1359545):
    if i not in [1359519]:
        ls.append(extract_batting_data(series_id = 1345038, match_id = i))  # series_id = ipl year
for i in range(1370350, 1370353):
    ls.append(extract_batting_data(series_id = 1345038, match_id = i))

In [4]:
len(ls)

72

In [52]:
#for i in range(1370350, 1370353):
#    ls.append(extract_batting_data(series_id = 1345038, match_id = i))

In [35]:
#lsat match 1136620
ls = []
for i in range(1136576, 1136510):
    ls.append(extract_batting_data(series_id = 8048, match_id = i))

In [7]:
#change from 2022 "ipl" to indian-premier-league
url ='https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/match-schedule-fixtures-and-results'     #change ipl for few urls 2019-18-17
reqs = requests.get(url)
soup = BeautifulSoup(reqs.text, 'html.parser')
urls = []
for link in soup.find_all('a', href=True):
    if link['href'].endswith('full-scorecard'):
        if 'indian-premier-league' in link['href']:      #change ipl for few urls 2019-18-17
            urls.append(link['href'].replace('full-scorecard', 'match-impact-player'))

In [8]:
urls

['/series/indian-premier-league-2023-1345038/sunrisers-hyderabad-vs-punjab-kings-14th-match-1359488/match-impact-player',
 '/series/indian-premier-league-2023-1345038/gujarat-titans-vs-kolkata-knight-riders-13th-match-1359487/match-impact-player',
 '/series/indian-premier-league-2023-1345038/gujarat-titans-vs-chennai-super-kings-1st-match-1359475/match-impact-player',
 '/series/indian-premier-league-2023-1345038/punjab-kings-vs-kolkata-knight-riders-2nd-match-1359476/match-impact-player',
 '/series/indian-premier-league-2023-1345038/lucknow-super-giants-vs-delhi-capitals-3rd-match-1359477/match-impact-player',
 '/series/indian-premier-league-2023-1345038/sunrisers-hyderabad-vs-rajasthan-royals-4th-match-1359478/match-impact-player',
 '/series/indian-premier-league-2023-1345038/royal-challengers-bangalore-vs-mumbai-indians-5th-match-1359479/match-impact-player',
 '/series/indian-premier-league-2023-1345038/chennai-super-kings-vs-lucknow-super-giants-6th-match-1359480/match-impact-player',
 '/series/indian-premier-league-2023-1345038/delhi-capitals-vs-gujarat-titans-7th-match-1359481/match-impact-player',
 '/series/indian-premier-league-2023-1345038/rajasthan-royals-vs-punjab-kings-8th-match-1359482/match-impact-player',
 '/series/indian-premier-league-2023-1345038/kolkata-knight-riders-vs-royal-challengers-bangalore-9th-match-1359483/match-impact-player',
 '/series/indian-premier-league-2023-1345038/lucknow-super-giants-vs-sunrisers-hyderabad-10th-match-1359484/match-impact-player',
 '/series/indian-premier-league-2023-1345038/rajasthan-royals-vs-delhi-capitals-11th-match-1359485/match-impact-player',
 '/series/indian-premier-league-2023-1345038/mumbai-indians-vs-chennai-super-kings-12th-match-1359486/match-impact-player',
 '/series/indian-premier-league-2023-1345038/gujarat-titans-vs-kolkata-knight-riders-13th-match-1359487/match-impact-player',
 '/series/indian-premier-league-2023-1345038/sunrisers-hyderabad-vs-punjab-kings-14th-match-1359488/match-impact-player']

In [4]:
def extract_Impact_data(match_id):
    URL = 'https://www.espncricinfo.com'+ str(match_id)
    return URL

In [5]:
#lsat match 1136620
impact_url = []
for i in urls:
    impact_url.append(extract_Impact_data(match_id = i))

In [6]:
impact_url

['https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/sunrisers-hyderabad-vs-punjab-kings-14th-match-1359488/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/gujarat-titans-vs-kolkata-knight-riders-13th-match-1359487/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/gujarat-titans-vs-chennai-super-kings-1st-match-1359475/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/punjab-kings-vs-kolkata-knight-riders-2nd-match-1359476/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/lucknow-super-giants-vs-delhi-capitals-3rd-match-1359477/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/sunrisers-hyderabad-vs-rajasthan-royals-4th-match-1359478/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/royal-challengers-bangalore-vs-mumbai-indians-5th-match-1359479/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/chennai-super-kings-vs-lucknow-super-giants-6th-match-1359480/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/delhi-capitals-vs-gujarat-titans-7th-match-1359481/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/rajasthan-royals-vs-punjab-kings-8th-match-1359482/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/kolkata-knight-riders-vs-royal-challengers-bangalore-9th-match-1359483/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/lucknow-super-giants-vs-sunrisers-hyderabad-10th-match-1359484/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/rajasthan-royals-vs-delhi-capitals-11th-match-1359485/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/mumbai-indians-vs-chennai-super-kings-12th-match-1359486/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/gujarat-titans-vs-kolkata-knight-riders-13th-match-1359487/match-impact-player',
 'https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/sunrisers-hyderabad-vs-punjab-kings-14th-match-1359488/match-impact-player']

In [5]:
df_list = []
for i, url in enumerate(ls):
    df_bat1dump  = pd.read_html(url)[0]
    df_bat1dump['counter'] = i+1
    df_list.append(df_bat1dump)
df_bat1dump = pd.concat(df_list)

df_list = []
for i, url in enumerate(ls):
    df_bowl1dump  = pd.read_html(url)[1]
    df_bowl1dump['counter'] = i+1
    df_list.append(df_bowl1dump)
df_bowl1dump = pd.concat(df_list)

df_list = []
for i, url in enumerate(ls):
    df_bat2dump  = pd.read_html(url)[2]
    df_bat2dump['counter'] = i+1
    df_list.append(df_bat2dump)
df_bat2dump = pd.concat(df_list)

df_list = []
for i, url in enumerate(ls):
    df_bowl2dump  = pd.read_html(url)[3]
    df_bowl2dump['counter'] = i+1
    df_list.append(df_bowl2dump)
df_bowl2dump = pd.concat(df_list)

## Venue date ipl records details apart from scorecard

In [70]:
df_list = []
for i, url in enumerate(ls):
    df_data  = pd.read_html(url)[4]
    df_list.append(df_data)
df_data = pd.concat(df_list)
#pull data for t20debut
df_list = []
for i, url in enumerate(ls):
    df_data2  = pd.read_html(url)[4]
    df_data2['counter'] = i+1
    df_list.append(df_data2)
df_data2 = pd.concat(df_list)

In [56]:
print(df_data.shape)
print(df_data2.shape)

(934, 2)
(934, 3)

In [71]:
df_data_index = df_data.index
df_data2_index = df_data2.index

In [48]:
col1 = df_data2.columns

In [7]:
df_data.to_csv('df_data.csv',header=df_data.columns, index=False, encoding='utf-8' )
df_data2.to_csv('df_data2.csv',header=df_data2.columns, index=False, encoding='utf-8' )

In [189]:
# #IPL2023 playoff
# ls = []
# for i in range(1370350, 1370353):
#     ls.append(extract_batting_data(series_id = 1345038, match_id = i))
# len(ls)
# df_list = []
# for i, url in enumerate(ls):
#     df_data  = pd.read_html(url)[4]
#     df_data = df_data[~df_data[0].isin(['Series result'])]
#     df_list.append(df_data)
# df_data_play = pd.concat(df_list)
# #pull data for t20debut
# df_list = []
# i = 71
# for i, url in enumerate(ls):
#     df_data2  = pd.read_html(url)[4]
#     df_data2 = df_data[~df_data[0].isin(['Series result'])]
#     df_data2['counter'] = 70+i+1
#     df_list.append(df_data2)
# df_data2_play = pd.concat(df_list)
# df_data_play.reset_index(drop=True,inplace=True)
# # df_data2_play.reset_index(drop=True,inplace=True)
# cre_index = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
# new_index = cre_index * 3   #4 play of round
# df_data_play.index = new_index
# df_data2_play.index = new_index
# df_data_index = df_data_leg.index.tolist()
# df_data2_index = df_data2_leg.index.tolist()
# df_data_index.extend(new_index)
# df_data2_index.extend(new_index)

# df_data = pd.concat([df_data_leg,df_data_play],ignore_index=True,sort=True)
# df_data2 = pd.concat([df_data2_leg,df_data2_play],ignore_index=True,sort= False)

# df_data.index = df_data_index
# df_data2.index = df_data2_index

# df_data_1 = df_data[~df_data[0].isin(['T20 debut'])]    #IPL 2023 impact players remove
# df_data_noimp = df_data_1[~df_data_1[0].str.endswith('Replacement')]

In [ ]:
#df_data = df_data[~df_data[0].isin(['Series result'])]
#my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
#new_index = my_list * 72   #change accodingly to no matches len(ls)

In [14]:
#T20 debut 
#Series result
#df_data_1 = df_data[~df_data[0].isin(['T20 debut'])]

In [15]:
# T20 debut players only
#df_data_2 = df_data[df_data[0].isin(['T20 debut'])]

### # T20 debut players only

In [83]:
df_data = pd.read_csv('df_data.csv',header=None,skiprows = 1)
df_data2 = pd.read_csv('df_data2.csv',header=None,skiprows = 1)
df_data2.columns = col1

In [84]:
df_data.set_index([df_data_index],inplace=True)
df_data2.set_index([df_data2_index],inplace=True)

In [85]:
print(df_data.shape)
print(df_data2.shape)

(934, 2)
(934, 3)

In [87]:
df_data_2 = df_data2[df_data2[0].isin(['T20 debut'])]
df_data_2.reset_index(drop=True,inplace=True)
result = [re.findall('[A-Z][^A-Z]*',x) for x in  df_data_2[1]]
debut20 = pd.DataFrame(result)
debut20['T20_debut_1'] = debut20[0] + ' ' +debut20[1]
debut20['T20_debut_2'] = debut20[2] + ' ' + debut20[3]
debut20['T20_debut_2'].fillna('None',inplace=True)
debut20 = debut20[['T20_debut_1','T20_debut_2']]
df_debut20 = pd.concat([debut20,df_data_2['counter']],axis=1)

Replacementdump = df_data2[df_data2[0].str.endswith('Replacement')]


Replacementdump.head()

impact_team = Replacementdump.pivot(values=0,  columns = 'counter').T
dict = {
        "DC Player Replacement" : 'Delhi Capitals', 
        "LSG Player Replacement" : 'Lucknow Super Giants',
        "GT Player Replacement": 'Gujarat Titans',
        "KKR Player Replacement": 'Kolkata Knight Riders',
        "PBKS Player Replacement" : 'Punjab Kings', 
        "RR Player Replacement": 'Rajasthan Royals',
        "SRH Player Replacement": 'Sunrisers Hyderabad',
        "MI Player Replacement": 'Mumbai Indians',
        "RCB Player Replacement": 'Royal Challengers Bangalore',
        "CSK Player Replacement": 'Chennai Super Kings'
         }


impact_team.replace({6: dict,7:dict},inplace=True)
impact_team.reset_index(inplace=True)
impact_team.columns = ['counter','impactTeam1','impactTeam2']

Replacement = Replacementdump.pivot(values=1,  columns = 'counter').T

Replacement.reset_index(inplace=True)

Replacement.columns = ['counter','ImpactTeam1','ImpactTeam2']

def impact(df):
    df1 = df.str.split(":",expand=True)
    df2 = df1[1].str.split(r'in\s*\,',expand=True)
    df3 = df2[1].str.split(r'out\s*\(',expand=True)
    df_final = pd.concat([df2[0],df3[0]],axis=1)
    df_final.fillna('None',inplace=True)
    return df_final

impactTeam1 = impact(Replacement['ImpactTeam1'])
impactTeam1.columns = ['ImpactPlayers1','Replace1Player1']
impactTeam1[impactTeam1.columns] = impactTeam1.apply(lambda x:x.str.strip())


impactTeam2 = impact(Replacement['ImpactTeam2'])
impactTeam2.columns = ['ImpactPlayers2','ReplacePlayer2']
impactTeam2[impactTeam2.columns] = impactTeam2.apply(lambda x:x.str.strip())


df_impact = pd.concat([impactTeam1,impactTeam2,impact_team],axis=1)
df_impact.fillna('None',inplace=True)

In [88]:
# IPL 2023
df_data_1 = df_data[~df_data[0].isin(['T20 debut'])]    #IPL 2023 impact players remove
df_data_noimp = df_data_1[~df_data_1[0].str.endswith('Replacement')]

df_data_noimp.reset_index(drop=True,inplace=True)
for i in range(len(df_data_noimp)):
    df_data_noimp.loc[i,'indexold'] = i %11
df_data_1cpy = df_data_noimp.copy(deep=True)
df_data_clean = df_data_1cpy.assign(group=df_data_1cpy.index//11).pivot(index='group', values=1, columns='indexold')
df_data_clean['counter'] = df_data_clean.index +1

df_data_1.reset_index(drop=True,inplace=True)

for i in range(len(df_data_1)):
    df_data_1.loc[i,'indexold'] = i %12

df_data_1cpy = df_data_1.copy(deep=True)

df_data_1cpy.head(15)

C:\Users\vigne\AppData\Local\Temp\ipykernel_20340\2692196154.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data_noimp.loc[i,'indexold'] = i %11
C:\Users\vigne\AppData\Local\Temp\ipykernel_20340\2692196154.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data_1.loc[i,'indexold'] = i %12

,0,1,indexold
0,"Narendra Modi Stadium, Ahmedabad","Narendra Modi Stadium, Ahmedabad",0.0
1,Toss,"Gujarat Titans, elected to field first",1.0
2,Series,Indian Premier League,2.0
3,Season,2023,3.0
4,Player Of The Match,Rashid Khan,4.0
5,Match days,31 March 2023 - night (20-over match),5.0
6,GT Player Replacement,"Impact player: Sai Sudharsan in, Kane Williams...",6.0
7,CSK Player Replacement,"Impact player: Tushar Deshpande in, Ambati Ray...",7.0
8,Umpires,Nitin MenonDRSSaiyed KhalidDRS,8.0
9,TV Umpire,Virender Sharma,9.0
10,Reserve Umpire,Abhijit Bengeri,10.0
11,Match Referee,Javagal Srinath,11.0
12,Points,"Gujarat Titans 2, Chennai Super Kings 0",0.0
13,"Punjab Cricket Association IS Bindra Stadium, ...","Punjab Cricket Association IS Bindra Stadium, ...",1.0
14,Toss,"Kolkata Knight Riders, elected to field first",2.0

In [89]:
df_data_clean['counter'] = df_data_clean.index +1

df_data_clean.columns = ['Stadium','Toss','Series','Season','Player Of The Match','Match days','Umpires','TV_Umpire','Res_Umpire','Match_Ref','Points','counter']

Teams = df_data_clean['Points'].str.split(',',expand=True).replace('\d+', '', regex=True)
won_team = df_data_clean['Points'].str.split(',',expand=True)[0]
Teams.columns = ['Team1','Team2']

Teams['Team1'] = Teams['Team1'].str.strip()

Teams['Team2'] = Teams['Team2'].str.strip()

Toss = df_data_clean['Toss'].str.split(',',expand=True)

Toss_team = pd.DataFrame(Toss[0])

Toss_team.columns =['Toss_team']

bat_field= Toss[1].str.split(' ',expand=True)

bat_field = pd.DataFrame(bat_field[3])

bat_field.columns = ['bat_field']

bat_field = bat_field['bat_field'].str.strip()

#MatchDate = pd.to_datetime(df_data_clean['Match days'].str.slice(start=0,stop = 13))
MatchDate = pd.to_datetime(df_data_clean['Match days'].str.split(r'-',expand=True)[0])

MatchDate = pd.DataFrame(MatchDate)

MatchDate = MatchDate.rename(columns={MatchDate.columns[0]: 'Date'})

Umpires = df_data_clean['Umpires'].str.strip()
df_umpclean = Umpires.str.split("DRS",expand=True).iloc[:,:2]
df_umpclean.columns = ['Umpires1','Umpires2']

fram = [df_data_clean,Teams,Toss_team,bat_field,MatchDate,df_umpclean]

dfs = pd.concat(fram,axis=1)

In [13]:
# dfs = []
# for j in Umpires:
#     if 'Bruce OxenfordYeshwant Barde' in j:
#         result = re.findall('[A-Z][^A-Z]*', j)
#         dfs.append([' '.join(result[i:i+2]) for i in range(0, len(result), 2)])
#     else:
#         dfs.append(j.str.split("DRS",expand=True))

In [14]:
# def split_name(name):
#     pattern = r'([A-Z][a-z]+)'
#     matches = re.findall(pattern, name)
#     return matches

In [90]:
dfs['second_innings'] = np.where((dfs['bat_field'] == 'field') & (dfs['Toss_team'] == dfs['Team1']), 
                            dfs['Team1'],
                            np.where((dfs['bat_field'] == 'field') & (dfs['Toss_team'] == dfs['Team2']),
                                     dfs['Team2'],
                                     np.where((dfs['bat_field'] == 'bat') & (dfs['Toss_team'] == dfs['Team1']), 
                                              dfs['Team2'],
                                              np.where((dfs['bat_field'] == 'bat') & (dfs['Toss_team'] == dfs['Team2']), 
                                                       dfs['Team1'],
                                                       dfs['bat_field']))))

dfs['First_innings'] = np.where((dfs['bat_field'] == 'bat') & (dfs['Toss_team'] == dfs['Team1']), 
                            dfs['Team1'],
                            np.where((dfs['bat_field'] == 'bat') & (dfs['Toss_team'] == dfs['Team2']),
                                     dfs['Team2'],
                                     np.where((dfs['bat_field'] == 'field') & (dfs['Toss_team'] == dfs['Team1']), 
                                              dfs['Team2'],
                                              np.where((dfs['bat_field'] == 'field') & (dfs['Toss_team'] == dfs['Team2']), 
                                                       dfs['Team1'],
                                                       dfs['bat_field']))))

dfs[['Team1','Team2','Toss_team','bat_field','second_innings','First_innings']]

,Team1,Team2,Toss_team,bat_field,second_innings,First_innings
group,,,,,,
0,Gujarat Titans,Chennai Super Kings,Gujarat Titans,field,Gujarat Titans,Chennai Super Kings
1,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,Punjab Kings
2,Lucknow Super Giants,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,Lucknow Super Giants
3,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,Rajasthan Royals
4,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,Mumbai Indians
...,...,...,...,...,...,...
67,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Mumbai Indians,Sunrisers Hyderabad
68,Gujarat Titans,Royal Challengers Bangalore,Gujarat Titans,field,Gujarat Titans,Royal Challengers Bangalore
69,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,Gujarat Titans,Chennai Super Kings
70,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,Lucknow Super Giants,Mumbai Indians
71,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,Gujarat Titans

In [93]:
dfs

,Stadium,Toss,Series,Season,Player Of The Match,Match days,Umpires,TV_Umpire,Res_Umpire,Match_Ref,...,counter,Team1_Won,Team2_lost,Toss_team,bat_field,Date,Umpires1,Umpires2,second_innings,First_innings
group,,,,,,,,,,,,,,,,,,,,,
0,"Narendra Modi Stadium, Ahmedabad","Gujarat Titans, elected to field first",Indian Premier League,2023,Rashid Khan,31 March 2023 - night (20-over match),Nitin MenonDRSSaiyed KhalidDRS,Virender Sharma,Abhijit Bengeri,Javagal Srinath,...,1,Gujarat Titans,Chennai Super Kings,Gujarat Titans,field,2023-03-31,Nitin Menon,Saiyed Khalid,Gujarat Titans,Chennai Super Kings
1,"Punjab Cricket Association IS Bindra Stadium, ...","Kolkata Knight Riders, elected to field first",Indian Premier League,2023,Arshdeep Singh,01 April 2023 - daynight (20-over match),Bruce OxenfordDRSYeshwant BardeDRS,Jayaraman Madanagopal,Pranav Joshi,Manu Nayyar,...,2,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,2023-04-01,Bruce Oxenford,Yeshwant Barde,Kolkata Knight Riders,Punjab Kings
2,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,"Delhi Capitals, elected to field first",Indian Premier League,2023,Mark Wood,01 April 2023 - night (20-over match),Anil ChaudharyDRSNikhil PatwardhanDRS,Sadashiv Iyer,Madanagopal Kuppuraj,Daniel Manohar,...,3,Lucknow Super Giants,Delhi Capitals,Delhi Capitals,field,2023-04-01,Anil Chaudhary,Nikhil Patwardhan,Delhi Capitals,Lucknow Super Giants
3,"Rajiv Gandhi International Stadium, Uppal, Hyd...","Sunrisers Hyderabad, elected to field first",Indian Premier League,2023,Jos Buttler,02 April 2023 - daynight (20-over match),KN AnanthapadmanabhanDRSRohan PanditDRS,Navdeep Singh,Abhijit Bhattacharya,Narayanan Kutty,...,4,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,2023-04-02,KN Ananthapadmanabhan,Rohan Pandit,Sunrisers Hyderabad,Rajasthan Royals
4,"M Chinnaswamy Stadium, Bengaluru","Royal Challengers Bangalore, elected to field ...",Indian Premier League,2023,Faf du Plessis,02 April 2023 - night (20-over match),Nitin MenonDRSTapan SharmaDRS,Virender Sharma,Abhijit Bengeri,Javagal Srinath,...,5,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,2023-04-02,Nitin Menon,Tapan Sharma,Royal Challengers Bangalore,Mumbai Indians
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,"Wankhede Stadium, Mumbai","Mumbai Indians, elected to field first",Indian Premier League,2023,Cameron Green,21 May 2023 - daynight (20-over match),KN AnanthapadmanabhanDRSRod TuckerDRS,Rohan Pandit,Parashar Joshi,Pankaj Dharmani,...,68,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,2023-05-21,KN Ananthapadmanabhan,Rod Tucker,Mumbai Indians,Sunrisers Hyderabad
68,"M Chinnaswamy Stadium, Bengaluru","Gujarat Titans, elected to field first",Indian Premier League,2023,Shubman Gill,21 May 2023 - night (20-over match),Nitin MenonDRSVirender SharmaDRS,Tapan Sharma,VM Dhokre,Javagal Srinath,...,69,Gujarat Titans,Royal Challengers Bangalore,Gujarat Titans,field,2023-05-21,Nitin Menon,Virender Sharma,Gujarat Titans,Royal Challengers Bangalore
69,"MA Chidambaram Stadium, Chepauk, Chennai","Gujarat Titans, elected to field first",Indian Premier League,2023,Ruturaj Gaikwad,23 May 2023 - night (20-over match),Anil ChaudharyDRSChris GaffaneyDRS,Bruce Oxenford,Virender Sharma,Manu Nayyar,...,70,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,2023-05-23,Anil Chaudhary,Chris Gaffaney,Gujarat Titans,Chennai Super Kings
70,"MA Chidambaram Stadium, Chepauk, Chennai","Mumbai Indians, elected to bat first",Indian Premier League,2023,Akash Madhwal,24 May 2023 - night (20-over match),Bruce OxenfordDRSVirender SharmaDRS,Chris Gaffaney,Anil Chaudhary,Narayanan Kutty,...,71,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,2023-05-24,Bruce Oxenford,Virender Sharma,Lucknow Super Giants,Mumbai Indians
71,"Narendra Modi Stadium, Ahmedabad","Mumbai Indians, elected to field first",Indian Premier League,2023,Shubman Gill,26 May 2023 - night (20-over match),Nitin MenonDRSRod TuckerDRS,Jayaraman Madanagopal,KN Ananthapadmanabhan,Javagal Srinath,...,72,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,2023-05-26,Nitin Menon,Rod Tucker,Mumbai Indians,Gujarat Titans

In [95]:
dfs = dfs.rename(columns={'Team1': 'Team1_Won','Team2': 'Team2_lost'})

match_cols = ['Date','Season','Toss_team','First_innings','second_innings','bat_field','Team1_Won','Team2_lost','Player Of The Match','Stadium','Umpires1','Umpires2', 'TV_Umpire', 'Res_Umpire', 'Match_Ref','counter']

df_clean_match = dfs[match_cols]

In [208]:
# df_clean_match.loc[df_clean_match["Umpires1"] == "Bruce OxenfordYeshwant Barde", "Umpires1"] = 'Bruce Oxenford'


# df_clean_match.loc[na_mask]

C:\Users\vigne\AppData\Local\Temp\ipykernel_10836\335005357.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_match['Umpires2'].fillna('Yeshwant Bard',inplace=True)

,Date,Season,Toss_team,First_innings,second_innings,bat_field,Team1_Won,Team2_lost,Player Of The Match,Stadium,Umpires1,Umpires2,TV_Umpire,Res_Umpire,Match_Ref,counter
group,,,,,,,,,,,,,,,,
1,2023-04-01,2023,Kolkata Knight Riders,Punjab Kings,Kolkata Knight Riders,field,Punjab Kings,Kolkata Knight Riders,Arshdeep Singh,"Punjab Cricket Association IS Bindra Stadium, ...",Bruce Oxenford,Yeshwant Bard,Jayaraman Madanagopal,Pranav Joshi,Manu Nayyar,2
60,2023-05-15,2023,Sunrisers Hyderabad,Gujarat Titans,Sunrisers Hyderabad,field,Gujarat Titans,Sunrisers Hyderabad,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Jayaraman Madanagopal,Yeshwant Bard,Akshay Totre,Mohamed Rafi,Manu Nayyar,61
67,2023-05-21,2023,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Mumbai Indians,Sunrisers Hyderabad,Cameron Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,Yeshwant Bard,Rohan Pandit,Parashar Joshi,Pankaj Dharmani,68

In [96]:
df_clean_match.sample(5)

,Date,Season,Toss_team,First_innings,second_innings,bat_field,Team1_Won,Team2_lost,Player Of The Match,Stadium,Umpires1,Umpires2,TV_Umpire,Res_Umpire,Match_Ref,counter
group,,,,,,,,,,,,,,,,
18,2023-04-14,2023,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders,field,Sunrisers Hyderabad,Kolkata Knight Riders,Harry Brook,"Eden Gardens, Kolkata",Chris Gaffaney,Sadashiv Iyer,Nikhil Patwardhan,Madanagopal Kuppuraj,Daniel Manohar,19
46,2023-05-05,2023,Rajasthan Royals,Rajasthan Royals,Gujarat Titans,bat,Gujarat Titans,Rajasthan Royals,Rashid Khan,"Sawai Mansingh Stadium, Jaipur",Saiyed Khalid,Virender Sharma,Nitin Menon,VM Dhokre,Javagal Srinath,47
36,2023-04-27,2023,Rajasthan Royals,Rajasthan Royals,Chennai Super Kings,bat,Rajasthan Royals,Chennai Super Kings,Yashasvi Jaiswal,"Sawai Mansingh Stadium, Jaipur",Akshay Totre,Yeshwant Barde,Rod Tucker,Mohamed Rafi,Manu Nayyar,37
14,2023-04-10,2023,Lucknow Super Giants,Royal Challengers Bangalore,Lucknow Super Giants,field,Lucknow Super Giants,Royal Challengers Bangalore,Nicholas Pooran,"M Chinnaswamy Stadium, Bengaluru",Anil Chaudhary,Nand Kishore,Chris Gaffaney,Madanagopal Kuppuraj,Daniel Manohar,15
7,2023-04-05,2023,Rajasthan Royals,Punjab Kings,Rajasthan Royals,field,Punjab Kings,Rajasthan Royals,Nathan Ellis,"Barsapara Cricket Stadium, Guwahati",KN Ananthapadmanabhan,Saidharshan Kumar,Rohan Pandit,Abhijit Bhattacharya,Narayanan Kutty,8

In [97]:
test_join = pd.merge(df_clean_match,df_impact,how = 'outer',on =['counter']).fillna('None')

test_join1 = pd.merge(test_join,df_debut20,how ='outer',on =['counter']).fillna('None')

test_join1.head()

,Date,Season,Toss_team,First_innings,second_innings,bat_field,Team1_Won,Team2_lost,Player Of The Match,Stadium,...,Match_Ref,counter,ImpactPlayers1,Replace1Player1,ImpactPlayers2,ReplacePlayer2,impactTeam1,impactTeam2,T20_debut_1,T20_debut_2
0,2023-03-31,2023,Gujarat Titans,Chennai Super Kings,Gujarat Titans,field,Gujarat Titans,Chennai Super Kings,Rashid Khan,"Narendra Modi Stadium, Ahmedabad",...,Javagal Srinath,1,Sai Sudharsan,Kane Williamson,Tushar Deshpande,Ambati Rayudu,Gujarat Titans,Chennai Super Kings,None,None
1,2023-04-01,2023,Kolkata Knight Riders,Punjab Kings,Kolkata Knight Riders,field,Punjab Kings,Kolkata Knight Riders,Arshdeep Singh,"Punjab Cricket Association IS Bindra Stadium, ...",...,Manu Nayyar,2,Rishi Dhawan,Bhanuka Rajapaksa,Venkatesh Iyer,Varun Chakravarthy,Punjab Kings,Kolkata Knight Riders,None,None
2,2023-04-01,2023,Delhi Capitals,Lucknow Super Giants,Delhi Capitals,field,Lucknow Super Giants,Delhi Capitals,Mark Wood,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,...,Daniel Manohar,3,Aman Hakim Khan,Khaleel Ahmed,Krishnappa Gowtham,Ayush Badoni,Delhi Capitals,Lucknow Super Giants,None,None
3,2023-04-02,2023,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,field,Rajasthan Royals,Sunrisers Hyderabad,Jos Buttler,"Rajiv Gandhi International Stadium, Uppal, Hyd...",...,Narayanan Kutty,4,Abdul Samad,Fazalhaq Farooqi,Navdeep Saini,Yashasvi Jaiswal,Sunrisers Hyderabad,Rajasthan Royals,None,None
4,2023-04-02,2023,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,Mumbai Indians,Faf du Plessis,"M Chinnaswamy Stadium, Bengaluru",...,Javagal Srinath,5,Jason Behrendorff,Suryakumar Yadav,None,None,Mumbai Indians,None,Arshad Khan,Nehal Wadhera

### remove T20 debut    & series result in all data

In [20]:
test_join1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35 entries, 0 to 34
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 35 non-null     datetime64[ns]
 1   Season               35 non-null     object
 2   Toss_team            35 non-null     object
 3   First_innings        35 non-null     object
 4   second_innings       35 non-null     object
 5   bat_field            35 non-null     object
 6   Team1_Won            35 non-null     object
 7   Team2_lost           35 non-null     object
 8   Player Of The Match  35 non-null     object
 9   Stadium              35 non-null     object
 10  Umpires1             35 non-null     object
 11  Umpires2             35 non-null     object
 12  TV_Umpire            35 non-null     object
 13  Res_Umpire           35 non-null     object
 14  Match_Ref            35 non-null     object
 15  counter              35 non-null     int64
 16  ImpactPlayers1       35 non-null     object
 17  Replace1Player1      35 non-null     object
 18  ImpactPlayers2       35 non-null     object
 19  ReplacePlayer2       35 non-null     object
 20  impactTeam1          35 non-null     object
 21  impactTeam2          35 non-null     object
 22  T20_debut_1          35 non-null     object
 23  T20_debut_2          35 non-null     object
dtypes: datetime64[ns](1), int64(1), object(22)
memory usage: 6.8+ KB

In [21]:
test_join1.columns

Index(['Date', 'Season', 'Toss_team', 'First_innings', 'second_innings',
       'bat_field', 'Team1_Won', 'Team2_lost', 'Player Of The Match',
       'Stadium', 'Umpires1', 'Umpires2', 'TV_Umpire', 'Res_Umpire',
       'Match_Ref', 'counter', 'ImpactPlayers1', 'Replace1Player1',
       'ImpactPlayers2', 'ReplacePlayer2', 'impactTeam1', 'impactTeam2',
       'T20_debut_1', 'T20_debut_2'],
      dtype='object')

In [22]:
#a = sum(df,[])
# df_list = []

# for i in range(len(ls)):
#      df_list.append(pd.DataFrame(df[i][0]))

# batting1_data = pd.concat(df_list, axis=0)

# String delimited

#split debutplayers
# string = "Abhishek SharmaSandeep Lamichhane"
# result = re.findall('[A-Z][^A-Z]*', string)
# print(result)

In [98]:
def clean_batting(batdump):
    batdump= batdump.iloc[:,[0,1,2,3,4,5,6,7,10]].dropna()
    batdump = batdump[(~batdump['BATTING'].str.startswith('Did not bat')) & (~batdump['BATTING'].str.startswith('Fall of wickets'))]   
    batdump.columns = ['batting','out','runs','balls','mins','fours','sixs','SR','counter']
    batdump.loc[batdump['mins'].str.contains('-'),'mins'] = 0
    batdump.loc[batdump['SR'].str.contains('-'),'SR'] = 0

    return batdump

def clean_bowling(dfs):
    dfs['R'] = pd.to_numeric(dfs['R'], errors='coerce')
    dfs = dfs.dropna()
    dfs.columns = ['BOWLING','over','Mins','Runs','Wicket','Economy','Zeros','fours','sixs','Wide','Noball','counter']
    dfs.loc[:, 'Runs'] = dfs.loc[:, 'Runs'].astype('int16')
    return dfs

bat1 = clean_batting(df_bat1dump)
bat2 = clean_batting(df_bat2dump)


bowl1 = clean_bowling(df_bowl1dump)
bowl2 = clean_bowling(df_bowl2dump)

test_join1.to_csv('IPL2023details.csv',header=test_join1.columns, index=False, encoding='utf-8' )
bat1.to_csv('batting1.csv',header=bat1.columns, index=False, encoding='utf-8' )
bat2.to_csv('batting2.csv',header=bat2.columns, index=False, encoding='utf-8' )
bowl1.to_csv('Bowling1.csv',header=bowl1.columns, index=False, encoding='utf-8' )
bowl2.to_csv('Bowling2.csv',header=bowl2.columns, index=False, encoding='utf-8' )

In [20]:
bat1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 291 entries, 0 to 13
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   batting  291 non-null    object
 1   out      291 non-null    object
 2   runs     291 non-null    object
 3   balls    291 non-null    object
 4   mins     291 non-null    object
 5   fours    291 non-null    object
 6   sixs     291 non-null    object
 7   SR       291 non-null    object
 8   counter  291 non-null    int64
dtypes: int64(1), object(8)
memory usage: 22.7+ KB

In [25]:
bowl2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 215 entries, 0 to 9
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   BOWLING  215 non-null    object
 1   over     215 non-null    object
 2   Mins     215 non-null    object
 3   Runs     215 non-null    int16
 4   Wicket   215 non-null    object
 5   Economy  215 non-null    object
 6   Zeros    215 non-null    object
 7   fours    215 non-null    object
 8   sixs     215 non-null    object
 9   Wide     215 non-null    object
 10  Noball   215 non-null    object
 11  counter  215 non-null    int64
dtypes: int16(1), int64(1), object(10)
memory usage: 20.6+ KB

In [111]:
bowl2

,BOWLING,over,Mins,Runs,Wicket,Economy,Zeros,fours,sixs,Wide,Noball,counter
0,Deepak Chahar,4,0,29,0,7.25,9,1,2,0,0,1
1,Tushar Deshpande,3.2,0,51,1,15.30,5,4,4,1,1,1
3,Rajvardhan Hangargekar,4,0,36,3,9.00,10,4,1,3,1,1
5,Mitchell Santner,4,0,32,0,8.00,7,5,0,0,0,1
6,Ravindra Jadeja,4,0,28,1,7.00,9,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2,Rashid Khan,4,0,33,1,8.25,9,4,1,0,0,30
4,Mohit Sharma,3,0,17,2,5.66,5,1,0,0,0,30
6,Noor Ahmad,4,0,18,2,4.50,13,1,0,0,0,30
8,Hardik Pandya,1,0,7,0,7.00,2,1,0,0,0,30
9,Rahul Tewatia,1,0,8,0,8.00,4,0,1,1,0,30

In [44]:
df_data.to_csv('test2.csv',header=df_data.columns, index=False, encoding='utf-8' )

In [ ]:
bowl2.to_csv('Bowling2.csv',header=bowl2.columns, index=False, encoding='utf-8' )